apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cwa.monitoringSecretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cwa.labels" . | nindent 4 }}
type: Opaque
data:
  CRUSOE_MONITORING_TOKEN: {{ .Values.monitoringToken | b64enc | quote }}
