services:
  crusoe-dcgm-exporter:
    image: nvidia/dcgm-exporter:${DCGM_EXPORTER_VERSION}
    container_name: crusoe-dcgm-exporter
    hostname: crusoe-dcgm-exporter
    cap_add: [SYS_ADMIN]
    volumes:
      - /etc/crusoe/crusoe_watch_agent/dcp-metrics-included.csv:/etc/dcgm-exporter/dcp-metrics-included.csv:ro
    env_file:
      - /etc/crusoe/crusoe_watch_agent/.env
    command: -f /etc/dcgm-exporter/dcp-metrics-included.csv -r localhost:5555 -a :${DCGM_EXPORTER_PORT:-9400}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host
    restart: always
