apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cwaUpdater.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cwaUpdater.labels" . | nindent 4 }}
